var config = `
{
    "metric": {
        "lights": "LightsOff",
        "season": "summer",
        "road": "hwy",
        "wheels": "Wheels19",
        "ac": "acOff",
        "aero": "off",
        "driving": "off",
        "windows": "WindowsUp",
        "temperatureIndex": 2,
        "temperature": 20,
        "outsideTempsTop": [0, -45, -85, -120, -153, -176],
        "outsideTempsVals": [0, 33, 66, 100, 135, 165],
        "outsideTemps": [40, 30, 20, 10, 0, -10],
        "climateControlAPI": null,
        "drivingTypeAPI": null,
        "percentHighway": 100,
        "speed": 100,
        "speedVals": [120, 110, 100, 90, 80, 70],
        "panSpeeds": [35, 45, 55, 65, 75, 85],
        "wheelFPS": [50, 60, 70, 80, 90, 100],
        "speedRange": [70, 80, 90, 100, 110, 120],
        "speedIndex": 3,
        "speedAngle": 20,
        "popupTimeout":null,
        "isIE8":false,
        "running":false,
        "isImperial":false,
        "isHybrid":false,
        "currentBG": null,
        "currentRoad": null,
        "measurement": {
            "da_DK": "KM/T",
            "default":"KMH"
        },
        "summerWinterCutoff": 0,
        "summerWinterACCutoff": 10,
        "speedRangeMin": 70,
        "speedRangeMax": 120,
        "speedLabel": "KM",
        "drivingEfficiency": 182,
        "plugEfficiencyStd": 6.48,
        "plugEfficiencyMid": 9.94,
        "plugEfficiencyMid_JP": 6.743,
        "plugEfficiencyHi": 19.85,
        "plugEfficiencyHi_JP": 13.65,
        "maxMiles": 500,
        "savingsTitles": ["PETROL STATIONS", "OIL CHANGES", "SPARK PLUGS", "SMOG CHECKS", "TIMING BELTS", "FUEL FILTERS"],
        "rangeScrollTop": 699,
        "chargingScrollTop": 3533,
        "roadTripsScrollTop": 6793,
        "electricityScrollTop": 10686,
        "savingsScrollTop": 10066,
        "rangeSectionStart": 2711,
        "rangeSectionStop": 3457,
        "chargingSectionStart": 5440,
        "chargingSectionStop": 6048,
        "roadTripsSectionStart": 9248,
        "roadTripsSectionStop": 10026,
        "electricitySectionStart": 12506,
        "electricitySectionStop": 13266,
        "savingsSectionStart": 10515,
        "savingsSectionStop": 13226,
        "rangeSectionPauseStart": 0,
        "rangeSectionPauseStop": 2701,
        "chargingSectionPauseStart": 2901,
        "chargingSectionPauseStop": 5968,
        "roadTripsSectionPauseStart": 6168,
        "roadTripsSectionPauseStop": 9294,
        "electricitySectionPauseStart": 9494,
        "electricitySectionPauseStop": 12561,
        "savingsSectionPauseStart": 12761,
        "savingsSectionPauseStop": 15844
    }
}
`;
